### ISSUE TITLE
Scoreboards are no longer working in 1.20.4

### ISSUE THREAD

**Issue by Exos9** [Efnilite/Walk-in-the-Park#114] opened 2024-01-14 19:55 UTC
**Describe the bug**
Scoreboards only show the title in 1.20.4. No further information is shown, and an error is printed in the logs

**To Reproduce**
1. Install IP 5.1.2 on a server running 1.20.4
2. Start the server
3. Join a parkour game
4. Scoreboard only shows the title

**Screenshots**
![2024-01-14_20 52 20](https://github.com/Efnilite/Walk-in-the-Park/assets/17933834/89a5ac82-eb2f-4be9-9acc-eefb60258b47)

**Errors**
These are the errors printed in the log:
`[20:48:17 WARN]: [IP] Task #16 for IP v5.1.2 generated an exception
java.lang.RuntimeException: Unable to update scoreboard lines
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.updateLines(FastBoardBase.java:350) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.player.ParkourUser.updateScoreboard(ParkourUser.java:276) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.generator.ParkourGenerator.lambda$tick$5(ParkourGenerator.java:402) ~[IP-5.1.2.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.efnilite.ip.generator.ParkourGenerator.tick(ParkourGenerator.java:400) ~[IP-5.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2124]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2124]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1666) ~[purpur-1.20.4.jar:git-Purpur-2124]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2124]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1545) ~[purpur-1.20.4.jar:git-Purpur-2124]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2124]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2124]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field net.minecraft.network.protocol.game.PacketPlayOutScoreboardScore.a to java.lang.String
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79) ~[?:?]
        at java.lang.reflect.Field.set(Field.java:799) ~[?:?]
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.setField(FastBoardBase.java:559) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.sendScorePacket(FastBoardBase.java:475) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.updateLines(FastBoardBase.java:338) ~[IP-5.1.2.jar:?]
        ... 12 more`

**Versions**
- IP 5.1.2
- Purpur 1.20.4 running build 2124
- Also tested on Paper 1.20.4

**Comment by AlmostPanda** [comment] 2024-01-14 20:54
I think its fixed in new version 5.1.3, which is not available yet

**Comment by Efnilite** [comment] 2024-01-14 20:55
Duplicate of #112 :)

**Closed by Efnilite** 2024-01-14 20:55 UTC
Labels: bug

**Comment by Exos9** [comment] 2024-01-14 21:49
> Duplicate of #112 :)

Indeed, I did not see the older issue as it was closed, my bad!
