### ISSUE TITLE
(!) You can't do this right now.

### ISSUE THREAD

**Issue by LucidAPs** [Efnilite/Walk-in-the-Park#67] opened 2022-01-15 10:00 UTC
No one can join, please fix it.
Using version 2.8g
![image](https://user-images.githubusercontent.com/42933023/149617754-c6a526bb-e462-4d3b-8c30-c39bcd357a72.png)

There is no other messages on console or anything else.

**Comment by Efnilite** [comment] 2022-01-15 10:13
You've disabled joining in the config or you have enabled permissions. Set `joining` to false or give players the `witp.join` perm ;)

**Comment by LucidAPs** [comment] 2022-01-15 10:30
No change, already done.
![image](https://user-images.githubusercontent.com/42933023/149618575-ed592c95-6669-4ae1-8aee-22aeec6c1ec0.png)

**Comment by Efnilite** [comment] 2022-01-15 10:33
Thats really weird. Can you try disabling permissions and use /witp reload and then check again? To make sure this is an issue with the permissions

**Comment by LucidAPs** [comment] 2022-01-15 10:35
Disabled perms and reloaded, still the same message.

**Comment by LucidAPs** [comment] 2022-01-15 10:42
If it helps, I faced this issue with previous versions aswell. Its not something that was introduced on the last two three versions.

**Comment by Efnilite** [comment] 2022-01-15 10:42
I'll take a look, thanks for the info :)

**Comment by Efnilite** [comment] 2022-01-15 11:20
Does this only occur with the /witp join command or others which require permissions as well? /witp leaderboard, etc.

**Comment by LucidAPs** [comment] 2022-01-15 11:51
All other commands work just fine.

**Comment by Efnilite** [comment] 2022-01-15 12:00
> All other commands work just fine.

If that's the case then the cause was probably the if statement being turned around, sorry for the inconvenience but it should be fixed now. However, if it isn't fixed in the next release, feel free to open another issue and you can refer to this one :)

**Closed by Efnilite** 2022-01-15 12:00 UTC
Labels: bug
